### ISSUE TITLE
persistent mongodb storage mount database file on the host directory volume

### ISSUE THREAD

**Issue by xianlin** [tutumcloud/mongodb#29]
I am using the tutum/mongodb docker image, how to mount external volume and use it as the database persistant storage for `/data/db`

**Comment by sukrit007** [comment]
You could possible use -v option provided by docker and give an external path:
```
docker run -v /mnt/external-mount:/data/db  -d -p 27017:27017 -p 28017:28017 tutum/mongodb
```

**Comment by fermayo** [comment]
Like @sukrit007 says :)
